### ISSUE TITLE
Non-Postgres compatibility

### ISSUE THREAD

**Issue by mariadb-BryanAlsdorf** [oliwarner/django-multifactor#2]
First off, thanks for this project. I was working with django-mfa2 as a POC and had decided I was going to have to re-write everything from scratch.

My company however uses MariaDB and Django currently does not support JSONField on any database besides Postgres. [This looks to be changing in 3.1](https://github.com/django/django/pull/11452), but that is a ways off.

As a general concept, would you be interesting in supporting other database backends? Either through [this library](https://pypi.org/project/jsonfield2/) or by extracting the properties field out into multiple models?

I'll be implementing this for my use and would prefer to have it merged upstream as well if you are open.

Thanks!

**Comment by oliwarner** [comment]
Postgres's JSONField does a little more than just storing JSON data. The Fido2 and U2F handlers both perform deep queries (`ack properties__`). These could be separated out with a little thought but that would introduce plasticity too.

Going to JSONField2 would mean these factors to download the JSON blobs and filter them manually. It's possible, just a little non-optimal. It also won't work for a single-factor login (which isn't currently a goal, but it's nice to keep in mind) because you'd have to download **all** the data. Perhaps there is a way around this problem.

Without database queries, I feel like it would be a step back. If you can submit a PR that does this well, I'll honestly give it a serious look. A migration to preserve existing deployments is essential too.

The PR for Django 3.1 looks perfect though. Just 6 long months to go.

**Comment by mariadb-BryanAlsdorf** [comment]
The database queries can be converted to a text search, e.g. `properties__contains=f'"domain":"{request.get_host()}"',` but it is rather ugly.

Since there is a proper solution 6 months away it seems a waste of effort to hack something in now. I'll work off of a fork for now and try to send PR's for any non DB related items up stream. After 3.1 is released if the new JSONField works transparently and you are comfortable dropping support for earlier versions things should be able to converge.

**Comment by oliwarner** [comment]
I'll do a conditional import so that if models.JSONField exists, it uses that, and if it doesn't, it falls back to the Postgres-only field.

I know it's not ideal for you, but it does mean you get the choice between Postgres and using bleeding edge Django.

**Comment by oliwarner** [comment]
Django 3.1+ compat is in now for other databases.

Still in beta but I think the first RC is due any minute.
