### ISSUE TITLE
Adding a "Temporary Bypass" feature to ease unit and integration testing

### ISSUE THREAD

**Issue by Alireza2n** [oliwarner/django-multifactor#46]
@oliwarner 
Hi and thank you for the hard work on this package. 

### Requirement
When running integration or unit tests on decorated views, there is a need to temporary "bypass" or "disable" MFA enforcement so tests could run.
### Proposal
I'd propose adding a `DISABLE` key to the settings that when Django's `DEBUG` was on, bypasses MFA for decorated views.
### Suggestions
If you're on-board with my proposal I'd be happy to create a PR with this feature/improvement.

**Comment by StevenMapes** [comment]
Are you suggesting automatically disabling MFA when debug is on? If so I am strongly against this. There are times when you may need to turn debug on but still want MFA. Having a new setting variable which disables it makes more sense to me as then it's explicitly set which will make it clearer in my opinion

**Comment by Alireza2n** [comment]
@StevenMapes 
Not DEBUG alone but a combination of DEBUG and a new settings.

**Comment by oliwarner** [comment]
I'm implementing this in a way that's more suitable for @megges2000 than the way you've done it @Alireza2n 

`settings.MULTIFACTOR.BYPASS`, a path to a function that accepts the current request. If it returns `True`, you bypass multifactor, otherwise it continues as normal. This allows complicated things to be expressed quite simply:

    def bypass_when_impersonating(request):
        from loginas.utils import is_impersonated_session
        if is_impersonated_session(request):
            return True

    def bypass_when_debug(request):
        from django.config import settings
        return settings.DEBUG

I'm committing this code now (along with another burst of changes) with a view to getting this tested and making a major release soon. If you can test, please do. Note that the main branch contains breaking static changes too so make sure you do a collectstatic.

**Comment by oliwarner** [comment]
This is releasing with 0.6.0rc0. Please test if you can.

Before you upgrade, please note that **U2F has been removed** from this release (as browsers stop supporting it). Fido2/Webauthn is still in there. Don't want anyone to have any nasty shocks.
